apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  replicas: 1  # Sadece 1 pod
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher-asia
        image: snowy_publisher:v1.0
        imagePullPolicy: Never
        env:
        - name: SERVER_ADDRESS
          value: "http://weather-service.default.svc.cluster.local:15000"
        - name: CONTINENT
          value: "Asia"
      - name: publisher-europe
        image: snowy_publisher:v1.0
        imagePullPolicy: Never
        env:
        - name: SERVER_ADDRESS
          value: "http://weather-service.default.svc.cluster.local:15000"
        - name: CONTINENT
          value: "Europe"
      - name: publisher-africa
        image: snowy_publisher:v1.0
        imagePullPolicy: Never
        env:
        - name: SERVER_ADDRESS
          value: "http://weather-service.default.svc.cluster.local:15000"
        - name: CONTINENT
          value: "Africa"
      - name: publisher-namerica
        image: snowy_publisher:v1.0
        imagePullPolicy: Never
        env:
        - name: SERVER_ADDRESS
          value: "http://weather-service.default.svc.cluster.local:15000"
        - name: CONTINENT
          value: "North America"
      - name: publisher-samerica
        image: snowy_publisher:v1.0
        imagePullPolicy: Never
        env:
        - name: SERVER_ADDRESS
          value: "http://weather-service.default.svc.cluster.local:15000"
        - name: CONTINENT
          value: "South America"
      - name: publisher-australia
        image: snowy_publisher:v1.0
        imagePullPolicy: Never
        env:
        - name: SERVER_ADDRESS
          value: "http://weather-service.default.svc.cluster.local:15000"
        - name: CONTINENT
          value: "Australia"